#!/usr/bin/env python3
"""
GlucoSense — PPG Signal Header Generator
Writes ppg_signal.h containing:
  - HARDCODED_PPG[3000]: raw uint16_t samples, window [500:3500] matching
    the training pipeline (train_and_generate.py, line 36: ppg_signal[500:3500])
  - BUTTER_SOS[3][6]: exact Butterworth coefficients from scipy

Ground-truth feature values are taken directly from the training notebook:
  feat_df[['participant_id', *final_deploy_selected_features]].iloc[3]
They are NOT re-computed here — re-running the ML pipeline would be
redundant and risks introducing discrepancies with the original training.

Usage:
    source ../.venv/bin/activate
    python3 generate_ppg_header.py
Output:
    ppg_signal.h (same directory)
"""

import os
import numpy as np
import pandas as pd
from scipy.signal import butter

DATASET_PATH = '/home/bovage/Desktop/MY_PART_5/FYP/code/data/real/glucosense_r_dataset_2026-09-17.csv'
OUTPUT_PATH  = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ppg_signal.h')

SAMPLING_RATE = 50      # Hz
TARGET_ROW    = 3       # P003, fasting, BGL=110 mg/dL

# ─── Ground-truth features from feat_df.iloc[3] in the training notebook ───
# feat_df[['participant_id', *final_deploy_selected_features]].iloc[3]
GROUND_TRUTH = {
    'is_postprandial':   0.000000,
    'reflection_index':  0.983279,
    'peak_val':          0.882984,
    'dc_component':      40952.474667,
    'log_ac_dc_ratio':  -5.307745,
    'rms_val':           0.599915,
}

print("=== GlucoSense PPG Header Generator ===")

# ── 1. Load signal ──────────────────────────────────────────────────────────
df  = pd.read_csv(DATASET_PATH)
row = df.iloc[TARGET_ROW]

ppg_raw = np.array([float(x) for x in str(row['ppg_data']).split(';') if x.strip()])
# Window matches training notebook (real_data_ml_model_imputation_exp_hyper_params.ipynb):
#   active_signal = ppg_signal[250:3250]
# Previously wrong: ppg_raw[500:3500] (250 samples shifted relative to training)
active = ppg_raw[250:3250].astype(np.uint16)

is_postprandial = 0 if row['session_kind'] == 'fasting' else 1

print(f"Participant : {row['participant_id']}")
print(f"Session     : {row['session_kind']}")
print(f"BGL         : {row['bgl_mgdl']} mg/dL")
print(f"Window      : ppg_raw[250:3250] → {len(active)} samples @ {SAMPLING_RATE} Hz")
print(f"First 5 raw : {active[:5].tolist()}")
print()

assert len(active) == 3000, f"Expected 3000 samples, got {len(active)}"

# ── 2. Butterworth SOS coefficients ────────────────────────────────────────
sos = butter(3, [0.5, 8.0], btype='bandpass', fs=SAMPLING_RATE, output='sos')
print(f"Butterworth butter(3, [0.5,8.0], btype='bandpass', fs={SAMPLING_RATE})")
print(f"SOS shape: {sos.shape}")
for i, s in enumerate(sos):
    print(f"  Section {i}: b=[{s[0]:.15e}, {s[1]:.15e}, {s[2]:.15e}]")
    print(f"             a=[1.0, {s[4]:.15e}, {s[5]:.15e}]")
print()

# ── 3. Write ppg_signal.h ───────────────────────────────────────────────────
with open(OUTPUT_PATH, 'w') as f:
    f.write("""\
// ============================================================
// ppg_signal.h  —  Auto-generated by generate_ppg_header.py
//
// Source  : glucosense_r_dataset_2026-09-17.csv, Row 3
// Subject : P003, fasting, BGL=110 mg/dL
// Window  : ppg_raw[250:3250]  →  3000 samples @ 50 Hz (60 s)
//           (matches training notebook: active_signal = ppg_signal[250:3250])
// ============================================================
#ifndef PPG_SIGNAL_H
#define PPG_SIGNAL_H

#define PPG_FS             50
#define PPG_LENGTH         3000
#define IS_POSTPRANDIAL    0
#define EXPECTED_BGL_MGDL  110

""")

    # ── Raw signal ────────────────────────────────────────────────────────
    f.write("// Raw PPG samples (uint16_t, MAX30100 IR channel)\n")
    f.write("static const uint16_t HARDCODED_PPG[PPG_LENGTH] PROGMEM = {\n")
    for i in range(0, len(active), 20):
        chunk = active[i:i + 20]
        comma = "," if i + 20 < len(active) else ""
        f.write("    " + ", ".join(str(v) for v in chunk) + comma + "\n")
    f.write("};\n\n")

    # ── Butterworth SOS ───────────────────────────────────────────────────
    f.write("// ── Butterworth Bandpass Filter Coefficients ────────────────\n")
    f.write("// scipy.signal.butter(3, [0.5, 8.0], btype='bandpass', fs=50, output='sos')\n")
    f.write("// Per section: [b0, b1, b2, a0=1.0, a1, a2]\n")
    f.write(f"#define BUTTER_N_SECTIONS  {sos.shape[0]}\n")
    f.write("static const double BUTTER_SOS[BUTTER_N_SECTIONS][6] = {\n")
    for i, s in enumerate(sos):
        comma = "," if i < len(sos) - 1 else ""
        f.write(f"    {{ {s[0]:.15e}, {s[1]:.15e}, {s[2]:.15e},"
                f" 1.0, {s[4]:.15e}, {s[5]:.15e} }}{comma}\n")
    f.write("};\n\n")

    # ── Ground-truth features ─────────────────────────────────────────────
    f.write("// ── Ground-Truth Feature Values ─────────────────────────────\n")
    f.write("// From: feat_df[['participant_id', *final_deploy_selected_features]].iloc[3]\n")
    f.write("// (training notebook — NOT recomputed here)\n")
    order = ['is_postprandial','reflection_index','peak_val','dc_component','log_ac_dc_ratio','rms_val']
    for idx, name in enumerate(order):
        f.write(f"// input[{idx}] {name:20s} = {GROUND_TRUTH[name]:.8f}\n")
    f.write("\n#endif // PPG_SIGNAL_H\n")

print(f"✓  ppg_signal.h written → {OUTPUT_PATH}")
